name: Arxiv Summarizer

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 00:02 UTC, which is 08:02 Beijing Time (UTC+8)
    - cron: "2 0 * * 1-5"

jobs:
  run_summarizer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Arxiv Summarizer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          OPENAI_MODEL_NAME: ${{ vars.OPENAI_MODEL_NAME }}
          SUMMARY_LANGUAGE: ${{ vars.SUMMARY_LANGUAGE }}
        run: python arxiv_summarizer.py eess.AS --user_interest "audio signal processing, spatial audio, active noise cancellation, speech signal processing" --filter_level "mid"
